package com.mall.cn.dao.mapper;

import com.mall.cn.model.CmsHelp;
import com.mall.cn.model.CmsHelpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsHelpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    int countByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    int deleteByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    int insert(CmsHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    int insertSelective(CmsHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    List<CmsHelp> selectByExampleWithBLOBs(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    List<CmsHelp> selectByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CmsHelp record, @Param("example") CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CmsHelp record, @Param("example") CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CmsHelp record, @Param("example") CmsHelpExample example);
}