package com.mall.cn.dao.mapper;

import com.mall.cn.model.CmsSubject;
import com.mall.cn.model.CmsSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int countByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int deleteByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int insert(CmsSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int insertSelective(CmsSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    List<CmsSubject> selectByExampleWithBLOBs(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    List<CmsSubject> selectByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CmsSubject record, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CmsSubject record, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CmsSubject record, @Param("example") CmsSubjectExample example);
}