package com.mall.cn.dao.mapper;

import com.mall.cn.model.CmsTopic;
import com.mall.cn.model.CmsTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int countByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int deleteByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int insert(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int insertSelective(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    List<CmsTopic> selectByExampleWithBLOBs(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    List<CmsTopic> selectByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CmsTopic record, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CmsTopic record, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CmsTopic record, @Param("example") CmsTopicExample example);
}