package com.mall.cn.dao.mapper;

import com.mall.cn.model.OmsOrderReturnApply;
import com.mall.cn.model.OmsOrderReturnApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsOrderReturnApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int countByExample(OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int deleteByExample(OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int insert(OmsOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int insertSelective(OmsOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    List<OmsOrderReturnApply> selectByExample(OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OmsOrderReturnApply record, @Param("example") OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OmsOrderReturnApply record, @Param("example") OmsOrderReturnApplyExample example);
}