package com.mall.cn.dao.mapper;

import com.mall.cn.model.PmsProductLadder;
import com.mall.cn.model.PmsProductLadderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductLadderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbggenerated
     */
    int countByExample(PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbggenerated
     */
    int deleteByExample(PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbggenerated
     */
    int insert(PmsProductLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbggenerated
     */
    int insertSelective(PmsProductLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbggenerated
     */
    List<PmsProductLadder> selectByExample(PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PmsProductLadder record, @Param("example") PmsProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_ladder
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PmsProductLadder record, @Param("example") PmsProductLadderExample example);
}