package com.mall.cn.dao.mapper;

import com.mall.cn.model.UmsMemberTag;
import com.mall.cn.model.UmsMemberTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbggenerated
     */
    int countByExample(UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbggenerated
     */
    int deleteByExample(UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbggenerated
     */
    int insert(UmsMemberTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbggenerated
     */
    int insertSelective(UmsMemberTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbggenerated
     */
    List<UmsMemberTag> selectByExample(UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UmsMemberTag record, @Param("example") UmsMemberTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UmsMemberTag record, @Param("example") UmsMemberTagExample example);
}