package com.mall.cn.dao.mapper;

import com.mall.cn.model.UmsMemberTask;
import com.mall.cn.model.UmsMemberTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbggenerated
     */
    int countByExample(UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbggenerated
     */
    int deleteByExample(UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbggenerated
     */
    int insert(UmsMemberTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbggenerated
     */
    int insertSelective(UmsMemberTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbggenerated
     */
    List<UmsMemberTask> selectByExample(UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UmsMemberTask record, @Param("example") UmsMemberTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UmsMemberTask record, @Param("example") UmsMemberTaskExample example);
}