package com.mall.cn.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_help_category
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class CmsHelpCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_help_category.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_help_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   分类图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_help_category.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   专题数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_help_category.help_count
     *
     * @mbggenerated
     */
    private Integer helpCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_help_category.show_status
     *
     * @mbggenerated
     */
    private Integer showStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_help_category.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_help_category.id
     *
     * @return the value of cms_help_category.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_help_category.id
     *
     * @param id the value for cms_help_category.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_help_category.name
     *
     * @return the value of cms_help_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_help_category.name
     *
     * @param name the value for cms_help_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_help_category.icon
     *
     * @return the value of cms_help_category.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_help_category.icon
     *
     * @param icon the value for cms_help_category.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_help_category.help_count
     *
     * @return the value of cms_help_category.help_count
     *
     * @mbggenerated
     */
    public Integer getHelpCount() {
        return helpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_help_category.help_count
     *
     * @param helpCount the value for cms_help_category.help_count
     *
     * @mbggenerated
     */
    public void setHelpCount(Integer helpCount) {
        this.helpCount = helpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_help_category.show_status
     *
     * @return the value of cms_help_category.show_status
     *
     * @mbggenerated
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_help_category.show_status
     *
     * @param showStatus the value for cms_help_category.show_status
     *
     * @mbggenerated
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_help_category.sort
     *
     * @return the value of cms_help_category.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_help_category.sort
     *
     * @param sort the value for cms_help_category.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}