package com.mall.cn.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_member_report
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class CmsMemberReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_member_report.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   举报类型：0->商品评价；1->话题内容；2->用户评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_member_report.report_type
     *
     * @mbggenerated
     */
    private Integer reportType;

    /**
     * Database Column Remarks:
     *   举报人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_member_report.report_member_name
     *
     * @mbggenerated
     */
    private String reportMemberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_member_report.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_member_report.report_object
     *
     * @mbggenerated
     */
    private String reportObject;

    /**
     * Database Column Remarks:
     *   举报状态：0->未处理；1->已处理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_member_report.report_status
     *
     * @mbggenerated
     */
    private Integer reportStatus;

    /**
     * Database Column Remarks:
     *   处理结果：0->无效；1->有效；2->恶意
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_member_report.handle_status
     *
     * @mbggenerated
     */
    private Integer handleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_member_report.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_member_report.id
     *
     * @return the value of cms_member_report.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_member_report.id
     *
     * @param id the value for cms_member_report.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_member_report.report_type
     *
     * @return the value of cms_member_report.report_type
     *
     * @mbggenerated
     */
    public Integer getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_member_report.report_type
     *
     * @param reportType the value for cms_member_report.report_type
     *
     * @mbggenerated
     */
    public void setReportType(Integer reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_member_report.report_member_name
     *
     * @return the value of cms_member_report.report_member_name
     *
     * @mbggenerated
     */
    public String getReportMemberName() {
        return reportMemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_member_report.report_member_name
     *
     * @param reportMemberName the value for cms_member_report.report_member_name
     *
     * @mbggenerated
     */
    public void setReportMemberName(String reportMemberName) {
        this.reportMemberName = reportMemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_member_report.create_time
     *
     * @return the value of cms_member_report.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_member_report.create_time
     *
     * @param createTime the value for cms_member_report.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_member_report.report_object
     *
     * @return the value of cms_member_report.report_object
     *
     * @mbggenerated
     */
    public String getReportObject() {
        return reportObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_member_report.report_object
     *
     * @param reportObject the value for cms_member_report.report_object
     *
     * @mbggenerated
     */
    public void setReportObject(String reportObject) {
        this.reportObject = reportObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_member_report.report_status
     *
     * @return the value of cms_member_report.report_status
     *
     * @mbggenerated
     */
    public Integer getReportStatus() {
        return reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_member_report.report_status
     *
     * @param reportStatus the value for cms_member_report.report_status
     *
     * @mbggenerated
     */
    public void setReportStatus(Integer reportStatus) {
        this.reportStatus = reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_member_report.handle_status
     *
     * @return the value of cms_member_report.handle_status
     *
     * @mbggenerated
     */
    public Integer getHandleStatus() {
        return handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_member_report.handle_status
     *
     * @param handleStatus the value for cms_member_report.handle_status
     *
     * @mbggenerated
     */
    public void setHandleStatus(Integer handleStatus) {
        this.handleStatus = handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_member_report.note
     *
     * @return the value of cms_member_report.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_member_report.note
     *
     * @param note the value for cms_member_report.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}