package com.mall.cn.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table oms_company_address
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class OmsCompanyAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   地址名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.address_name
     *
     * @mbggenerated
     */
    private String addressName;

    /**
     * Database Column Remarks:
     *   默认发货地址：0->否；1->是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.send_status
     *
     * @mbggenerated
     */
    private Integer sendStatus;

    /**
     * Database Column Remarks:
     *   是否默认收货地址：0->否；1->是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.receive_status
     *
     * @mbggenerated
     */
    private Integer receiveStatus;

    /**
     * Database Column Remarks:
     *   收发货人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   收货人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   省/直辖市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.region
     *
     * @mbggenerated
     */
    private String region;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_company_address.detail_address
     *
     * @mbggenerated
     */
    private String detailAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.id
     *
     * @return the value of oms_company_address.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.id
     *
     * @param id the value for oms_company_address.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.address_name
     *
     * @return the value of oms_company_address.address_name
     *
     * @mbggenerated
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.address_name
     *
     * @param addressName the value for oms_company_address.address_name
     *
     * @mbggenerated
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.send_status
     *
     * @return the value of oms_company_address.send_status
     *
     * @mbggenerated
     */
    public Integer getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.send_status
     *
     * @param sendStatus the value for oms_company_address.send_status
     *
     * @mbggenerated
     */
    public void setSendStatus(Integer sendStatus) {
        this.sendStatus = sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.receive_status
     *
     * @return the value of oms_company_address.receive_status
     *
     * @mbggenerated
     */
    public Integer getReceiveStatus() {
        return receiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.receive_status
     *
     * @param receiveStatus the value for oms_company_address.receive_status
     *
     * @mbggenerated
     */
    public void setReceiveStatus(Integer receiveStatus) {
        this.receiveStatus = receiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.name
     *
     * @return the value of oms_company_address.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.name
     *
     * @param name the value for oms_company_address.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.phone
     *
     * @return the value of oms_company_address.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.phone
     *
     * @param phone the value for oms_company_address.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.province
     *
     * @return the value of oms_company_address.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.province
     *
     * @param province the value for oms_company_address.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.city
     *
     * @return the value of oms_company_address.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.city
     *
     * @param city the value for oms_company_address.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.region
     *
     * @return the value of oms_company_address.region
     *
     * @mbggenerated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.region
     *
     * @param region the value for oms_company_address.region
     *
     * @mbggenerated
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_company_address.detail_address
     *
     * @return the value of oms_company_address.detail_address
     *
     * @mbggenerated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_company_address.detail_address
     *
     * @param detailAddress the value for oms_company_address.detail_address
     *
     * @mbggenerated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }
}