package com.mall.cn.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table oms_cart_item
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class OmsCartItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_sku_id
     *
     * @mbggenerated
     */
    private Long productSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * Database Column Remarks:
     *   购买数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   添加到购物车的价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   销售属性1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.sp1
     *
     * @mbggenerated
     */
    private String sp1;

    /**
     * Database Column Remarks:
     *   销售属性2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.sp2
     *
     * @mbggenerated
     */
    private String sp2;

    /**
     * Database Column Remarks:
     *   销售属性3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.sp3
     *
     * @mbggenerated
     */
    private String sp3;

    /**
     * Database Column Remarks:
     *   商品主图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_pic
     *
     * @mbggenerated
     */
    private String productPic;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   商品副标题（卖点）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_sub_title
     *
     * @mbggenerated
     */
    private String productSubTitle;

    /**
     * Database Column Remarks:
     *   商品sku条码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_sku_code
     *
     * @mbggenerated
     */
    private String productSkuCode;

    /**
     * Database Column Remarks:
     *   会员昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.member_nickname
     *
     * @mbggenerated
     */
    private String memberNickname;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.delete_status
     *
     * @mbggenerated
     */
    private Integer deleteStatus;

    /**
     * Database Column Remarks:
     *   商品分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_category_id
     *
     * @mbggenerated
     */
    private Long productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_brand
     *
     * @mbggenerated
     */
    private String productBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_sn
     *
     * @mbggenerated
     */
    private String productSn;

    /**
     * Database Column Remarks:
     *   商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_attr
     *
     * @mbggenerated
     */
    private String productAttr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.id
     *
     * @return the value of oms_cart_item.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.id
     *
     * @param id the value for oms_cart_item.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_id
     *
     * @return the value of oms_cart_item.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_id
     *
     * @param productId the value for oms_cart_item.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_sku_id
     *
     * @return the value of oms_cart_item.product_sku_id
     *
     * @mbggenerated
     */
    public Long getProductSkuId() {
        return productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_sku_id
     *
     * @param productSkuId the value for oms_cart_item.product_sku_id
     *
     * @mbggenerated
     */
    public void setProductSkuId(Long productSkuId) {
        this.productSkuId = productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.member_id
     *
     * @return the value of oms_cart_item.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.member_id
     *
     * @param memberId the value for oms_cart_item.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.quantity
     *
     * @return the value of oms_cart_item.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.quantity
     *
     * @param quantity the value for oms_cart_item.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.price
     *
     * @return the value of oms_cart_item.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.price
     *
     * @param price the value for oms_cart_item.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.sp1
     *
     * @return the value of oms_cart_item.sp1
     *
     * @mbggenerated
     */
    public String getSp1() {
        return sp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.sp1
     *
     * @param sp1 the value for oms_cart_item.sp1
     *
     * @mbggenerated
     */
    public void setSp1(String sp1) {
        this.sp1 = sp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.sp2
     *
     * @return the value of oms_cart_item.sp2
     *
     * @mbggenerated
     */
    public String getSp2() {
        return sp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.sp2
     *
     * @param sp2 the value for oms_cart_item.sp2
     *
     * @mbggenerated
     */
    public void setSp2(String sp2) {
        this.sp2 = sp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.sp3
     *
     * @return the value of oms_cart_item.sp3
     *
     * @mbggenerated
     */
    public String getSp3() {
        return sp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.sp3
     *
     * @param sp3 the value for oms_cart_item.sp3
     *
     * @mbggenerated
     */
    public void setSp3(String sp3) {
        this.sp3 = sp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_pic
     *
     * @return the value of oms_cart_item.product_pic
     *
     * @mbggenerated
     */
    public String getProductPic() {
        return productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_pic
     *
     * @param productPic the value for oms_cart_item.product_pic
     *
     * @mbggenerated
     */
    public void setProductPic(String productPic) {
        this.productPic = productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_name
     *
     * @return the value of oms_cart_item.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_name
     *
     * @param productName the value for oms_cart_item.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_sub_title
     *
     * @return the value of oms_cart_item.product_sub_title
     *
     * @mbggenerated
     */
    public String getProductSubTitle() {
        return productSubTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_sub_title
     *
     * @param productSubTitle the value for oms_cart_item.product_sub_title
     *
     * @mbggenerated
     */
    public void setProductSubTitle(String productSubTitle) {
        this.productSubTitle = productSubTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_sku_code
     *
     * @return the value of oms_cart_item.product_sku_code
     *
     * @mbggenerated
     */
    public String getProductSkuCode() {
        return productSkuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_sku_code
     *
     * @param productSkuCode the value for oms_cart_item.product_sku_code
     *
     * @mbggenerated
     */
    public void setProductSkuCode(String productSkuCode) {
        this.productSkuCode = productSkuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.member_nickname
     *
     * @return the value of oms_cart_item.member_nickname
     *
     * @mbggenerated
     */
    public String getMemberNickname() {
        return memberNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.member_nickname
     *
     * @param memberNickname the value for oms_cart_item.member_nickname
     *
     * @mbggenerated
     */
    public void setMemberNickname(String memberNickname) {
        this.memberNickname = memberNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.create_date
     *
     * @return the value of oms_cart_item.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.create_date
     *
     * @param createDate the value for oms_cart_item.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.modify_date
     *
     * @return the value of oms_cart_item.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.modify_date
     *
     * @param modifyDate the value for oms_cart_item.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.delete_status
     *
     * @return the value of oms_cart_item.delete_status
     *
     * @mbggenerated
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.delete_status
     *
     * @param deleteStatus the value for oms_cart_item.delete_status
     *
     * @mbggenerated
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_category_id
     *
     * @return the value of oms_cart_item.product_category_id
     *
     * @mbggenerated
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_category_id
     *
     * @param productCategoryId the value for oms_cart_item.product_category_id
     *
     * @mbggenerated
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_brand
     *
     * @return the value of oms_cart_item.product_brand
     *
     * @mbggenerated
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_brand
     *
     * @param productBrand the value for oms_cart_item.product_brand
     *
     * @mbggenerated
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_sn
     *
     * @return the value of oms_cart_item.product_sn
     *
     * @mbggenerated
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_sn
     *
     * @param productSn the value for oms_cart_item.product_sn
     *
     * @mbggenerated
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_attr
     *
     * @return the value of oms_cart_item.product_attr
     *
     * @mbggenerated
     */
    public String getProductAttr() {
        return productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_attr
     *
     * @param productAttr the value for oms_cart_item.product_attr
     *
     * @mbggenerated
     */
    public void setProductAttr(String productAttr) {
        this.productAttr = productAttr;
    }
}