package com.mall.cn.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table oms_order_operate_history
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class OmsOrderOperateHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * Database Column Remarks:
     *   操作人：用户；系统；后台管理员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.operate_man
     *
     * @mbggenerated
     */
    private String operateMan;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.id
     *
     * @return the value of oms_order_operate_history.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.id
     *
     * @param id the value for oms_order_operate_history.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.order_id
     *
     * @return the value of oms_order_operate_history.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.order_id
     *
     * @param orderId the value for oms_order_operate_history.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.operate_man
     *
     * @return the value of oms_order_operate_history.operate_man
     *
     * @mbggenerated
     */
    public String getOperateMan() {
        return operateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.operate_man
     *
     * @param operateMan the value for oms_order_operate_history.operate_man
     *
     * @mbggenerated
     */
    public void setOperateMan(String operateMan) {
        this.operateMan = operateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.create_time
     *
     * @return the value of oms_order_operate_history.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.create_time
     *
     * @param createTime the value for oms_order_operate_history.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.order_status
     *
     * @return the value of oms_order_operate_history.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.order_status
     *
     * @param orderStatus the value for oms_order_operate_history.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.note
     *
     * @return the value of oms_order_operate_history.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.note
     *
     * @param note the value for oms_order_operate_history.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}