package com.mall.cn.model;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_product_ladder
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PmsProductLadder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_ladder.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_ladder.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * Database Column Remarks:
     *   满足的商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_ladder.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * Database Column Remarks:
     *   折扣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_ladder.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * Database Column Remarks:
     *   折后价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_ladder.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_ladder.id
     *
     * @return the value of pms_product_ladder.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_ladder.id
     *
     * @param id the value for pms_product_ladder.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_ladder.product_id
     *
     * @return the value of pms_product_ladder.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_ladder.product_id
     *
     * @param productId the value for pms_product_ladder.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_ladder.count
     *
     * @return the value of pms_product_ladder.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_ladder.count
     *
     * @param count the value for pms_product_ladder.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_ladder.discount
     *
     * @return the value of pms_product_ladder.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_ladder.discount
     *
     * @param discount the value for pms_product_ladder.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_ladder.price
     *
     * @return the value of pms_product_ladder.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_ladder.price
     *
     * @param price the value for pms_product_ladder.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}