package com.mall.cn.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_product_attribute_category
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PmsProductAttributeCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute_category.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   属性数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute_category.attribute_count
     *
     * @mbggenerated
     */
    private Integer attributeCount;

    /**
     * Database Column Remarks:
     *   参数数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute_category.param_count
     *
     * @mbggenerated
     */
    private Integer paramCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute_category.id
     *
     * @return the value of pms_product_attribute_category.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute_category.id
     *
     * @param id the value for pms_product_attribute_category.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute_category.name
     *
     * @return the value of pms_product_attribute_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute_category.name
     *
     * @param name the value for pms_product_attribute_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute_category.attribute_count
     *
     * @return the value of pms_product_attribute_category.attribute_count
     *
     * @mbggenerated
     */
    public Integer getAttributeCount() {
        return attributeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute_category.attribute_count
     *
     * @param attributeCount the value for pms_product_attribute_category.attribute_count
     *
     * @mbggenerated
     */
    public void setAttributeCount(Integer attributeCount) {
        this.attributeCount = attributeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute_category.param_count
     *
     * @return the value of pms_product_attribute_category.param_count
     *
     * @mbggenerated
     */
    public Integer getParamCount() {
        return paramCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute_category.param_count
     *
     * @param paramCount the value for pms_product_attribute_category.param_count
     *
     * @mbggenerated
     */
    public void setParamCount(Integer paramCount) {
        this.paramCount = paramCount;
    }
}