package com.mall.cn.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_product_category_attribute_relation
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PmsProductCategoryAttributeRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_category_attribute_relation.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_category_attribute_relation.product_category_id
     *
     * @mbggenerated
     */
    private Long productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_category_attribute_relation.product_attribute_id
     *
     * @mbggenerated
     */
    private Long productAttributeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_category_attribute_relation.id
     *
     * @return the value of pms_product_category_attribute_relation.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_category_attribute_relation.id
     *
     * @param id the value for pms_product_category_attribute_relation.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_category_attribute_relation.product_category_id
     *
     * @return the value of pms_product_category_attribute_relation.product_category_id
     *
     * @mbggenerated
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_category_attribute_relation.product_category_id
     *
     * @param productCategoryId the value for pms_product_category_attribute_relation.product_category_id
     *
     * @mbggenerated
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_category_attribute_relation.product_attribute_id
     *
     * @return the value of pms_product_category_attribute_relation.product_attribute_id
     *
     * @mbggenerated
     */
    public Long getProductAttributeId() {
        return productAttributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_category_attribute_relation.product_attribute_id
     *
     * @param productAttributeId the value for pms_product_category_attribute_relation.product_attribute_id
     *
     * @mbggenerated
     */
    public void setProductAttributeId(Long productAttributeId) {
        this.productAttributeId = productAttributeId;
    }
}