package com.mall.cn.model;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_product_full_reduction
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PmsProductFullReduction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_full_reduction.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_full_reduction.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_full_reduction.full_price
     *
     * @mbggenerated
     */
    private BigDecimal fullPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_full_reduction.reduce_price
     *
     * @mbggenerated
     */
    private BigDecimal reducePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_full_reduction.id
     *
     * @return the value of pms_product_full_reduction.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_full_reduction.id
     *
     * @param id the value for pms_product_full_reduction.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_full_reduction.product_id
     *
     * @return the value of pms_product_full_reduction.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_full_reduction.product_id
     *
     * @param productId the value for pms_product_full_reduction.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_full_reduction.full_price
     *
     * @return the value of pms_product_full_reduction.full_price
     *
     * @mbggenerated
     */
    public BigDecimal getFullPrice() {
        return fullPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_full_reduction.full_price
     *
     * @param fullPrice the value for pms_product_full_reduction.full_price
     *
     * @mbggenerated
     */
    public void setFullPrice(BigDecimal fullPrice) {
        this.fullPrice = fullPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_full_reduction.reduce_price
     *
     * @return the value of pms_product_full_reduction.reduce_price
     *
     * @mbggenerated
     */
    public BigDecimal getReducePrice() {
        return reducePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_full_reduction.reduce_price
     *
     * @param reducePrice the value for pms_product_full_reduction.reduce_price
     *
     * @mbggenerated
     */
    public void setReducePrice(BigDecimal reducePrice) {
        this.reducePrice = reducePrice;
    }
}