package com.mall.cn.model;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_sku_stock
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PmsSkuStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * Database Column Remarks:
     *   sku编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sku_code
     *
     * @mbggenerated
     */
    private String skuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * Database Column Remarks:
     *   预警库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.low_stock
     *
     * @mbggenerated
     */
    private Integer lowStock;

    /**
     * Database Column Remarks:
     *   销售属性1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sp1
     *
     * @mbggenerated
     */
    private String sp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sp2
     *
     * @mbggenerated
     */
    private String sp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sp3
     *
     * @mbggenerated
     */
    private String sp3;

    /**
     * Database Column Remarks:
     *   展示图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * Database Column Remarks:
     *   销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sale
     *
     * @mbggenerated
     */
    private Integer sale;

    /**
     * Database Column Remarks:
     *   单品促销价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.promotion_price
     *
     * @mbggenerated
     */
    private BigDecimal promotionPrice;

    /**
     * Database Column Remarks:
     *   锁定库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.lock_stock
     *
     * @mbggenerated
     */
    private Integer lockStock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.id
     *
     * @return the value of pms_sku_stock.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.id
     *
     * @param id the value for pms_sku_stock.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.product_id
     *
     * @return the value of pms_sku_stock.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.product_id
     *
     * @param productId the value for pms_sku_stock.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sku_code
     *
     * @return the value of pms_sku_stock.sku_code
     *
     * @mbggenerated
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sku_code
     *
     * @param skuCode the value for pms_sku_stock.sku_code
     *
     * @mbggenerated
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.price
     *
     * @return the value of pms_sku_stock.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.price
     *
     * @param price the value for pms_sku_stock.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.stock
     *
     * @return the value of pms_sku_stock.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.stock
     *
     * @param stock the value for pms_sku_stock.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.low_stock
     *
     * @return the value of pms_sku_stock.low_stock
     *
     * @mbggenerated
     */
    public Integer getLowStock() {
        return lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.low_stock
     *
     * @param lowStock the value for pms_sku_stock.low_stock
     *
     * @mbggenerated
     */
    public void setLowStock(Integer lowStock) {
        this.lowStock = lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sp1
     *
     * @return the value of pms_sku_stock.sp1
     *
     * @mbggenerated
     */
    public String getSp1() {
        return sp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sp1
     *
     * @param sp1 the value for pms_sku_stock.sp1
     *
     * @mbggenerated
     */
    public void setSp1(String sp1) {
        this.sp1 = sp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sp2
     *
     * @return the value of pms_sku_stock.sp2
     *
     * @mbggenerated
     */
    public String getSp2() {
        return sp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sp2
     *
     * @param sp2 the value for pms_sku_stock.sp2
     *
     * @mbggenerated
     */
    public void setSp2(String sp2) {
        this.sp2 = sp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sp3
     *
     * @return the value of pms_sku_stock.sp3
     *
     * @mbggenerated
     */
    public String getSp3() {
        return sp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sp3
     *
     * @param sp3 the value for pms_sku_stock.sp3
     *
     * @mbggenerated
     */
    public void setSp3(String sp3) {
        this.sp3 = sp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.pic
     *
     * @return the value of pms_sku_stock.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.pic
     *
     * @param pic the value for pms_sku_stock.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sale
     *
     * @return the value of pms_sku_stock.sale
     *
     * @mbggenerated
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sale
     *
     * @param sale the value for pms_sku_stock.sale
     *
     * @mbggenerated
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.promotion_price
     *
     * @return the value of pms_sku_stock.promotion_price
     *
     * @mbggenerated
     */
    public BigDecimal getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.promotion_price
     *
     * @param promotionPrice the value for pms_sku_stock.promotion_price
     *
     * @mbggenerated
     */
    public void setPromotionPrice(BigDecimal promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.lock_stock
     *
     * @return the value of pms_sku_stock.lock_stock
     *
     * @mbggenerated
     */
    public Integer getLockStock() {
        return lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.lock_stock
     *
     * @param lockStock the value for pms_sku_stock.lock_stock
     *
     * @mbggenerated
     */
    public void setLockStock(Integer lockStock) {
        this.lockStock = lockStock;
    }
}