package com.mall.cn.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_coupon
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SmsCoupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   优惠卷类型；0->全场赠券；1->会员赠券；2->购物赠券；3->注册赠券
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   使用平台：0->全部；1->移动；2->PC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.platform
     *
     * @mbggenerated
     */
    private Integer platform;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * Database Column Remarks:
     *   金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   每人限领张数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.per_limit
     *
     * @mbggenerated
     */
    private Integer perLimit;

    /**
     * Database Column Remarks:
     *   使用门槛；0表示无门槛
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.min_point
     *
     * @mbggenerated
     */
    private BigDecimal minPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * Database Column Remarks:
     *   使用类型：0->全场通用；1->指定分类；2->指定商品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.use_type
     *
     * @mbggenerated
     */
    private Integer useType;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * Database Column Remarks:
     *   发行数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.publish_count
     *
     * @mbggenerated
     */
    private Integer publishCount;

    /**
     * Database Column Remarks:
     *   已使用数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.use_count
     *
     * @mbggenerated
     */
    private Integer useCount;

    /**
     * Database Column Remarks:
     *   领取数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.receive_count
     *
     * @mbggenerated
     */
    private Integer receiveCount;

    /**
     * Database Column Remarks:
     *   可以领取的日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.enable_time
     *
     * @mbggenerated
     */
    private Date enableTime;

    /**
     * Database Column Remarks:
     *   优惠码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   可领取的会员类型：0->无限时
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.member_level
     *
     * @mbggenerated
     */
    private Integer memberLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.id
     *
     * @return the value of sms_coupon.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.id
     *
     * @param id the value for sms_coupon.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.type
     *
     * @return the value of sms_coupon.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.type
     *
     * @param type the value for sms_coupon.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.name
     *
     * @return the value of sms_coupon.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.name
     *
     * @param name the value for sms_coupon.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.platform
     *
     * @return the value of sms_coupon.platform
     *
     * @mbggenerated
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.platform
     *
     * @param platform the value for sms_coupon.platform
     *
     * @mbggenerated
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.count
     *
     * @return the value of sms_coupon.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.count
     *
     * @param count the value for sms_coupon.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.amount
     *
     * @return the value of sms_coupon.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.amount
     *
     * @param amount the value for sms_coupon.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.per_limit
     *
     * @return the value of sms_coupon.per_limit
     *
     * @mbggenerated
     */
    public Integer getPerLimit() {
        return perLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.per_limit
     *
     * @param perLimit the value for sms_coupon.per_limit
     *
     * @mbggenerated
     */
    public void setPerLimit(Integer perLimit) {
        this.perLimit = perLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.min_point
     *
     * @return the value of sms_coupon.min_point
     *
     * @mbggenerated
     */
    public BigDecimal getMinPoint() {
        return minPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.min_point
     *
     * @param minPoint the value for sms_coupon.min_point
     *
     * @mbggenerated
     */
    public void setMinPoint(BigDecimal minPoint) {
        this.minPoint = minPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.start_time
     *
     * @return the value of sms_coupon.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.start_time
     *
     * @param startTime the value for sms_coupon.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.end_time
     *
     * @return the value of sms_coupon.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.end_time
     *
     * @param endTime the value for sms_coupon.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.use_type
     *
     * @return the value of sms_coupon.use_type
     *
     * @mbggenerated
     */
    public Integer getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.use_type
     *
     * @param useType the value for sms_coupon.use_type
     *
     * @mbggenerated
     */
    public void setUseType(Integer useType) {
        this.useType = useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.note
     *
     * @return the value of sms_coupon.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.note
     *
     * @param note the value for sms_coupon.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.publish_count
     *
     * @return the value of sms_coupon.publish_count
     *
     * @mbggenerated
     */
    public Integer getPublishCount() {
        return publishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.publish_count
     *
     * @param publishCount the value for sms_coupon.publish_count
     *
     * @mbggenerated
     */
    public void setPublishCount(Integer publishCount) {
        this.publishCount = publishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.use_count
     *
     * @return the value of sms_coupon.use_count
     *
     * @mbggenerated
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.use_count
     *
     * @param useCount the value for sms_coupon.use_count
     *
     * @mbggenerated
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.receive_count
     *
     * @return the value of sms_coupon.receive_count
     *
     * @mbggenerated
     */
    public Integer getReceiveCount() {
        return receiveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.receive_count
     *
     * @param receiveCount the value for sms_coupon.receive_count
     *
     * @mbggenerated
     */
    public void setReceiveCount(Integer receiveCount) {
        this.receiveCount = receiveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.enable_time
     *
     * @return the value of sms_coupon.enable_time
     *
     * @mbggenerated
     */
    public Date getEnableTime() {
        return enableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.enable_time
     *
     * @param enableTime the value for sms_coupon.enable_time
     *
     * @mbggenerated
     */
    public void setEnableTime(Date enableTime) {
        this.enableTime = enableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.code
     *
     * @return the value of sms_coupon.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.code
     *
     * @param code the value for sms_coupon.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon.member_level
     *
     * @return the value of sms_coupon.member_level
     *
     * @mbggenerated
     */
    public Integer getMemberLevel() {
        return memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon.member_level
     *
     * @param memberLevel the value for sms_coupon.member_level
     *
     * @mbggenerated
     */
    public void setMemberLevel(Integer memberLevel) {
        this.memberLevel = memberLevel;
    }
}