package com.mall.cn.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_flash_promotion_log
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SmsFlashPromotionLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_log.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_log.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_log.member_phone
     *
     * @mbggenerated
     */
    private String memberPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_log.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   会员订阅时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_log.subscribe_time
     *
     * @mbggenerated
     */
    private Date subscribeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_flash_promotion_log.send_time
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.id
     *
     * @return the value of sms_flash_promotion_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.id
     *
     * @param id the value for sms_flash_promotion_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.member_id
     *
     * @return the value of sms_flash_promotion_log.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.member_id
     *
     * @param memberId the value for sms_flash_promotion_log.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.product_id
     *
     * @return the value of sms_flash_promotion_log.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.product_id
     *
     * @param productId the value for sms_flash_promotion_log.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.member_phone
     *
     * @return the value of sms_flash_promotion_log.member_phone
     *
     * @mbggenerated
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.member_phone
     *
     * @param memberPhone the value for sms_flash_promotion_log.member_phone
     *
     * @mbggenerated
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.product_name
     *
     * @return the value of sms_flash_promotion_log.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.product_name
     *
     * @param productName the value for sms_flash_promotion_log.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.subscribe_time
     *
     * @return the value of sms_flash_promotion_log.subscribe_time
     *
     * @mbggenerated
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.subscribe_time
     *
     * @param subscribeTime the value for sms_flash_promotion_log.subscribe_time
     *
     * @mbggenerated
     */
    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.send_time
     *
     * @return the value of sms_flash_promotion_log.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.send_time
     *
     * @param sendTime the value for sms_flash_promotion_log.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }
}