package com.mall.cn.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_integration_consume_setting
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class UmsIntegrationConsumeSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   每一元需要抵扣的积分数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.deduction_per_amount
     *
     * @mbggenerated
     */
    private Integer deductionPerAmount;

    /**
     * Database Column Remarks:
     *   每笔订单最高抵用百分比
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.max_percent_per_order
     *
     * @mbggenerated
     */
    private Integer maxPercentPerOrder;

    /**
     * Database Column Remarks:
     *   每次使用积分最小单位100
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.use_unit
     *
     * @mbggenerated
     */
    private Integer useUnit;

    /**
     * Database Column Remarks:
     *   是否可以和优惠券同用；0->不可以；1->可以
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.coupon_status
     *
     * @mbggenerated
     */
    private Integer couponStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.id
     *
     * @return the value of ums_integration_consume_setting.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.id
     *
     * @param id the value for ums_integration_consume_setting.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.deduction_per_amount
     *
     * @return the value of ums_integration_consume_setting.deduction_per_amount
     *
     * @mbggenerated
     */
    public Integer getDeductionPerAmount() {
        return deductionPerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.deduction_per_amount
     *
     * @param deductionPerAmount the value for ums_integration_consume_setting.deduction_per_amount
     *
     * @mbggenerated
     */
    public void setDeductionPerAmount(Integer deductionPerAmount) {
        this.deductionPerAmount = deductionPerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.max_percent_per_order
     *
     * @return the value of ums_integration_consume_setting.max_percent_per_order
     *
     * @mbggenerated
     */
    public Integer getMaxPercentPerOrder() {
        return maxPercentPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.max_percent_per_order
     *
     * @param maxPercentPerOrder the value for ums_integration_consume_setting.max_percent_per_order
     *
     * @mbggenerated
     */
    public void setMaxPercentPerOrder(Integer maxPercentPerOrder) {
        this.maxPercentPerOrder = maxPercentPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.use_unit
     *
     * @return the value of ums_integration_consume_setting.use_unit
     *
     * @mbggenerated
     */
    public Integer getUseUnit() {
        return useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.use_unit
     *
     * @param useUnit the value for ums_integration_consume_setting.use_unit
     *
     * @mbggenerated
     */
    public void setUseUnit(Integer useUnit) {
        this.useUnit = useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.coupon_status
     *
     * @return the value of ums_integration_consume_setting.coupon_status
     *
     * @mbggenerated
     */
    public Integer getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.coupon_status
     *
     * @param couponStatus the value for ums_integration_consume_setting.coupon_status
     *
     * @mbggenerated
     */
    public void setCouponStatus(Integer couponStatus) {
        this.couponStatus = couponStatus;
    }
}