package com.mall.cn.model;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_member_rule_setting
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class UmsMemberRuleSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_rule_setting.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   连续签到天数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_rule_setting.continue_sign_day
     *
     * @mbggenerated
     */
    private Integer continueSignDay;

    /**
     * Database Column Remarks:
     *   连续签到赠送数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_rule_setting.continue_sign_point
     *
     * @mbggenerated
     */
    private Integer continueSignPoint;

    /**
     * Database Column Remarks:
     *   每消费多少元获取1个点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_rule_setting.consume_per_point
     *
     * @mbggenerated
     */
    private BigDecimal consumePerPoint;

    /**
     * Database Column Remarks:
     *   最低获取点数的订单金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_rule_setting.low_order_amount
     *
     * @mbggenerated
     */
    private BigDecimal lowOrderAmount;

    /**
     * Database Column Remarks:
     *   每笔订单最高获取点数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_rule_setting.max_point_per_order
     *
     * @mbggenerated
     */
    private Integer maxPointPerOrder;

    /**
     * Database Column Remarks:
     *   类型：0->积分规则；1->成长值规则
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_rule_setting.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.id
     *
     * @return the value of ums_member_rule_setting.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.id
     *
     * @param id the value for ums_member_rule_setting.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.continue_sign_day
     *
     * @return the value of ums_member_rule_setting.continue_sign_day
     *
     * @mbggenerated
     */
    public Integer getContinueSignDay() {
        return continueSignDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.continue_sign_day
     *
     * @param continueSignDay the value for ums_member_rule_setting.continue_sign_day
     *
     * @mbggenerated
     */
    public void setContinueSignDay(Integer continueSignDay) {
        this.continueSignDay = continueSignDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.continue_sign_point
     *
     * @return the value of ums_member_rule_setting.continue_sign_point
     *
     * @mbggenerated
     */
    public Integer getContinueSignPoint() {
        return continueSignPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.continue_sign_point
     *
     * @param continueSignPoint the value for ums_member_rule_setting.continue_sign_point
     *
     * @mbggenerated
     */
    public void setContinueSignPoint(Integer continueSignPoint) {
        this.continueSignPoint = continueSignPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.consume_per_point
     *
     * @return the value of ums_member_rule_setting.consume_per_point
     *
     * @mbggenerated
     */
    public BigDecimal getConsumePerPoint() {
        return consumePerPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.consume_per_point
     *
     * @param consumePerPoint the value for ums_member_rule_setting.consume_per_point
     *
     * @mbggenerated
     */
    public void setConsumePerPoint(BigDecimal consumePerPoint) {
        this.consumePerPoint = consumePerPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.low_order_amount
     *
     * @return the value of ums_member_rule_setting.low_order_amount
     *
     * @mbggenerated
     */
    public BigDecimal getLowOrderAmount() {
        return lowOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.low_order_amount
     *
     * @param lowOrderAmount the value for ums_member_rule_setting.low_order_amount
     *
     * @mbggenerated
     */
    public void setLowOrderAmount(BigDecimal lowOrderAmount) {
        this.lowOrderAmount = lowOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.max_point_per_order
     *
     * @return the value of ums_member_rule_setting.max_point_per_order
     *
     * @mbggenerated
     */
    public Integer getMaxPointPerOrder() {
        return maxPointPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.max_point_per_order
     *
     * @param maxPointPerOrder the value for ums_member_rule_setting.max_point_per_order
     *
     * @mbggenerated
     */
    public void setMaxPointPerOrder(Integer maxPointPerOrder) {
        this.maxPointPerOrder = maxPointPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.type
     *
     * @return the value of ums_member_rule_setting.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.type
     *
     * @param type the value for ums_member_rule_setting.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}